name: registry
version: v0
threads_nb: 2
port: 8800
log.file: /tmp/registry.log
db:
    mongo:
        host:
            host01:
                address: 'localhost:27017'
        database:
            db01:
                host: host01
                name: test_coco
        collection:
            collection01:
                database: db01
                name: registry
