name: registry
version: v0
threads_nb: 2
db:
    mongo:
        host:
            host01:
                address: 'localhost:27017'
        database:
            db01:
                host: host01
                name: db01
        collection:
            collection01:
                database: db01
                name: coll01
                
